package crypro

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: crypto.proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CryptoUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoUpdate) Reset() {
	*x = CryptoUpdate{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoUpdate) ProtoMessage() {}

func (x *CryptoUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoUpdate.ProtoReflect.Descriptor instead.
func (*CryptoUpdate) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *CryptoUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CryptoUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CryptoUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoUpdate) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CryptoUpdate) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

type CryptoUpdateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*CryptoUpdate        `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoUpdateList) Reset() {
	*x = CryptoUpdateList{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoUpdateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoUpdateList) ProtoMessage() {}

func (x *CryptoUpdateList) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CryptoUpdateList) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoUpdateList) GetUpdates() []*CryptoUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x12\x06crypto\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x01\n" +
	"\fCryptoUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\x01R\fcurrentPrice\"B\n" +
	"\x10CryptoUpdateList\x12.\n" +
	"\aupdates\x18\x01 \x03(\v2\x14.crypto.CryptoUpdateR\aupdates2W\n" +
	"\x0fMessageStreamer\x12D\n" +
	"\x0eStreamMessages\x12\x18.crypto.CryptoUpdateList\x1a\x16.google.protobuf.Empty(\x01B\x0fZ\rmodels/cryprob\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_crypto_proto_goTypes = []any{
	(*CryptoUpdate)(nil),     // 0: crypto.CryptoUpdate
	(*CryptoUpdateList)(nil), // 1: crypto.CryptoUpdateList
	(*emptypb.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_crypto_proto_depIdxs = []int32{
	0, // 0: crypto.CryptoUpdateList.updates:type_name -> crypto.CryptoUpdate
	1, // 1: crypto.MessageStreamer.StreamMessages:input_type -> crypto.CryptoUpdateList
	2, // 2: crypto.MessageStreamer.StreamMessages:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
